### PR TITLE
Resolve 33 product smile issues

### LINKED ISSUE #33: Product Smile Issue
@ogdenstudios It seems like on tablet displays the smiles are very large, can this be changes so they don't increase so large? Seems to occur in 1024px to 650px. Screenshot attached. Also at some resolutions it is no longer center with the phone.
image

### PR DESCRIPTION
**Pull request by ogdenstudios**
Resolves #33 

@baudoinalkali - I fixed the sizing. I set a max-width on the smile SVGs, so now they'll only get as wide as their containing element, which should fix them being too big on tablets. 

Then I bumped up the size of their containers on mobile sizes, and moved the `w-3/5` down to the images themselves. Now the container elements are full-width until the `lg` breakpoint. The phone images are `3/5` width, and the smile images are full width of their container. 

This fixes the issue for everything except that very first image on the product page. 

That looks fine on desktop views, but on mobile, we get something like this: 

Screen Shot 2021-05-23 at 3 29 51 PM

The problem is that we've got that margin left on it, which I imagine is there to offset the offset on the image itself. Do you want to try and fix this issue in this pull request, or do you want us to handle it separately?

### CODE REVIEW

**Comment by baudoinalkali** [comment]
@ogdenstudios Let's try to fix that. I think this is also related to that, but I also see they aren't really centered behind the device, they are a lot higher on smaller dimensions. 

image

**Comment by ogdenstudios** [comment]
Hmm, I think those are unrelated, but I can tackle them all the same. I'm going to pull this out into a component so I can keep them consistent.

**Comment by ogdenstudios** [comment]
@baudoinalkali - I fixed the responsive styles on those phone and smile components. I pulled it into its own component and swapped it out across the site. I've checked across phones/larger breakpoints and I think it's centered appropriately all over. 

I added alt tags to the images. I kept them blank on the smiles since those are decorations. For now they're also blank on the phones themselves, but since there's stuff in the text, we may have to consider writing some alt tags for those. 

We spoke in Upwork about splitting up `/images/product/more-applicants.png` into two separate images. While I wait on those separate images from you, I at least centered the smile behind the image itself. It looks crooked because of the composition of the image, but it's consistent with the phones. 

If you get me those separate images soon, I can wrap that up in this PR. But otherwise we could close this out and make the change in a different iteration. Up to you!

**Comment by ogdenstudios** [comment]
@baudoinalkali - I think that does it! Take a look and let me know. I'm probably signing off for the evening, but I think we're really close here and should be able to demo pretty well.

**Comment by ogdenstudios** [comment]
@baudoinalkali - I cleaned up the merge conflict stuff and pushed it back here. I took a look at the deployment and everything looks fine. It's worthwhile for you to triple check, just in case, but if you check the deploy preview and it looks good, then you're good to merge!

**Comment by baudoinalkali** [comment]
@ogdenstudios I noticed one issue on the homepage, everything else looks good.
image

**Comment by ogdenstudios** [comment]
Ope - got it. I had duplicated something during some rebasing. I think it's in good shape now.

**Pull request merged**
