### PR TITLE
add first pass at animation timer

### LINKED ISSUE #24: Animation MVP
As discussed let's have the smile appear in and then proceed to move in its current fashion.

### PR DESCRIPTION
**Pull request by ogdenstudios**
Resolves #24 

Hey @baudoinalkali - I'm not quite finished with this, but I want to pause here and see if you like the direction I'm headed in. This PR should give you a deploy preview to check out what I came up with. I put it on the `/about` page since I was just working on that anyway. 

Here's how it works:

1. On the `/about` page, we call the `useSmileObserver` custom hook. 
2. `useSmileObserver` takes an array of `useRef` objects. For every element we want to apply this to, we need to wrap it in a div and set it up as one of those refs. 
3. `useSmileObserver` calls `useEffect` just once. In that `useEffect` hook, it grabs the `current` value of each target ref we provided it. 
4. Then it loops through each `current` value and sets up an intersection observer for it, which watches the wrapper element.
5. When that wrapper element is scrolled into the viewport, we set the opacity to 1 (so we need to set its opacity to 0 originally, along with the transition duration, which I set to 500ms for now. 
6. I also have a `setTimeout` function, which waits for 500ms and then applies the `vert-move` class to the first child of the wrapper component. So the effect should be to wait for the element to become `opacity: 1` before it begins animation.

You can view this by just scrolling down the page. Or if you reload, the same thing will happen if you're at that scroll height. 

I figure before we close this out, we can tweak the values a little as needed. We can change the opacity transition, tweak the timeout, or anything else mentioned here. 

Once you're happy with that, I'll need to go through and apply this custom hook on all the pages you want the effect to happen, so I'll need to add it to the pages/components, and add the wrapper div/reference objects. 

Let me know what you think!

### CODE REVIEW

**Comment by baudoinalkali** [comment]
I like it. Let me run it by the client and make sure they are good with the appearance effect. They were talking about some other types of effects, so just want to nail that down now that they have something to reference.

**Comment by ogdenstudios** [comment]
@baudoinalkali - I've updated this PR, so the deploy preview should have the banner animation as well. You can check that out anywhere the orange banner appears. I specifically tested this with the homepage banner and I think it's looking good. Ready for review by you and the client.

**Comment by baudoinalkali** [comment]
@ogdenstudios Looks good, we are having a back and forth on if both should be animated. I'll update you once we make a decision. Personally I like it, but they are thinking it might be too much. I'm going to throw up some more items that you can work on in the meantime (assuming you have time).

**Comment by ogdenstudios** [comment]
@baudoinalkali - I just pushed what I can get to here. There's a few outstanding questions for you to provide guidance on:

1. The image on home for `/images/home-results.png` has the smile baked into the png, which I can't animate. If we want to add the appear/hover animation, we need to split that apart. 
2. I didn't touch any of the hero images, since those smile elements are also baked in, I believe.
3. I swapped out the `tailbg` classes on the about page for the banner elements. I think they have different padding, so it looks different than before, but now they're all consistent, so I think that's the right move anyway.
4. The footer class is basically the same `tailbg`, but green instead of orange. Do you want me to add the reveal and hover to that element as well? Or should that stay static?

**Comment by baudoinalkali** [comment]
1. That split apart version exists on the product page, I’ll add it though, no worries.
2. Yea they are baked in so all good there.
3. The text itself has different width to get text to fall onto multiple lines like their mock-up, I think we should be okay with how it is though.
4. Let’s keep it as is though. We’re discussing the specifics of the banner.

Separate question that related to the hero images. Is there anyway to better way to not have the background image cropped so much at large screen resolutions? For instance obviously the image needs to scale up to fit the large screen so some blurriness is completely understandable, but it seem like it’s just getting cut in half from top to bottom.

**Comment by ogdenstudios** [comment]
Oh, that makes sense. I pulled the floating one in from the product page. Pushing that now and I think this will be good to merge!

**Pull request merged**
