### PR TITLE
Mobile menu fixes

### LINKED ISSUE #43: Mobile Menu
I put together a mobile menu but there seems to be some alignment issues with regards to it expanding past the screen, not being fully centered, could you take a look at that? The code for the dropdown is [here](https://github.com/baudoinalkali/chattr/blob/main/components/Navigation/MobileDropdown.js).

### PR DESCRIPTION
**Pull request by ogdenstudios**
Resolves #43 

Not quite ready for review yet, but I wanted to show you a couple of quick tweaks I made, @baudoinalkali. The hamburger icon wasn't showing up for me, so I got that rendering. I also pushed the positioning so it's flush with the right side of the screen now. 

Can you tell me more about what you want resolved here? I see the buttons on the Dual CTAs are cut off. Is that part of this issue? You said:

>  there seems to be some alignment issues with regards to it expanding past the screen, not being fully centered

But I'm not precisely sure what you mean. I don't have a reference point in the PDF comps you've sent over. Is there a spec'd design for this, or do you have a clearer picture of what you want in your head?

### CODE REVIEW

**Comment by baudoinalkali** [comment]
@ogdenstudios I like how it's styled currently. I noticed the hamburger menu not showing up on all pages. This is what I see, I want the exact same look but centered on mobile devices, currently it's not perfectly centered. image

**Comment by ogdenstudios** [comment]
Ah, I think I understand what you mean. Check it out now - I made the button a block level element which eliminated the extra space on the bottom, and I got rid of the left margin on the SVG. 

Is that what you were looking for? If not, we might want to do a screen share so you can point me to the problem.

**Comment by baudoinalkali** [comment]
That was better. For some reason it's not perfectly centered. Also not sure if you're seeing this as well but there's a gap on the right only on the homepage. imageimage

**Comment by baudoinalkali** [comment]
Also the button size seems to be different on the homepage, attached product page for reference image

**Comment by ogdenstudios** [comment]
1. What do you want it to be centered in relation to? I think that's what I'm misunderstanding. As far as I can see, the SVG is centered inside the popover button, and the popover button is flexed to align center with the Chatter logo. Do you want that button centered horizontally so it's in the middle of the screen in the navbar?
2. I also see the gap, but I think it's unrelated to this component. If you take delete `<MobileNav />`, it still shows up.

**Comment by ogdenstudios** [comment]
@baudoinalkali - I think I finally got it. There were a few things going on here: 

1. The testimonial slider on the home page is what was causing the gap on the right hand side. I applied `overflow: hidden` to its wrapper and fixed that issue.
2. For whatever reason, using the `<Head />` component from Next.js is what was causing the mobile dropdown button to have different sizes. I honestly and truly do not know why - it's still baffling to me, lol. So I added it to every page, and then set the width of the button to 24px. Now they're all consistent, although you may want to go through and edit the data in the `Head` tags. I updated the title tag, but that's about it. 
3. I tweaked the sizing of the dropdown itself. It still isn't 100% of what you were describing in the video, but I think it's much closer. I'm about to sign off for the night, but if you want us to get closer on that, we might have to rework the component entirely. There are a few structural issues with it that prevent it from achieving the effect you're looking for. Basically we want to make the absolutely positioned element relative to a higher level component. Right now it's positioned relative to the button, so as the button's position moves around, its frame of reference is also moved around. We can make this easier to work with by setting it relative to the navbar itself, that way we always have 100% of the viewport width to work with. For now, I think this is closer. Let me know what you think and I can put a few more hours into redoing it for you if you prefer.

**Comment by baudoinalkali** [comment]
@ogdenstudios It seems to still be broken in a few places. Let's put a pause on this specific part, I want to make sure they are 100% on the menu design before we rework some of the elements to get the desired alignment and all of that.

**Comment by ogdenstudios** [comment]
@baudoinalkali - got it. If this still isn't meeting the mark I think we'll want to rebuild it from the ground up with whatever design spec we have.

**Pull request merged**
