### PR TITLE
Resolve 15 about page section

### LINKED ISSUE #15: About Page Section
Hey, so I was talking with the client about ways to introduce subtle animation. Something we wanted to play around with is animating the branding elements (the smile and tail). I made this mockup in Figma which has the svgs for everything, but the image/shape on the right are separate assets, as well as the smile. The subtle animation I was wanting to play around with was just a subtle up and down motion to add a little animation. Let me know if that makes sense and if that would be an okay thing to do elsewhere. 

Styles for page:
headline text (in the middle and in the blurb): text-4xl font-avantbold
text: text-xl font-proximasemi

For your reference, we're recreating this part of the current about page: 
image

https://www.figma.com/file/4NcynLyMr3eFfLtcVYA1Xg/Untitled?node-id=0%3A1

### PR DESCRIPTION
**Pull request by ogdenstudios**
Resolves #15 

@baudoinalkali - this PR should close out the about page section rework. Here's what I did: 

1. I made the smile SVG component reusable with different colors. Now you can set its color with `className="fill-current text-color-for-svg-here"`
2. I fixed a few JSX errors on the about page with incorrectly cased attributes
3. I made the about section in question responsive. I had to tweak some styles for that, but it's single column up until the large breakpoint, and then goes three columns from there on. 
4. I added the placeholder image from figma - it doesn't have the borders, but I figure when we get the actual image, you can swap it out with something that's been photoshopped to have the correct border around it. I put the blue shape behind it as a background image, so it should be easy to tweak image size and keep the background there.
5. I made your `vert-move` class standalone - now it doesn't require being attached to an `img` tag to work. Just drop `className="vert-move"` on anything to get that floating animation. 
6. I added a [prefers-reduced-motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) media query for the animation, so users who get motion sickness or otherwise don't want animations can opt out appropriately through their browser preferences.
7. I added the `vert-move` animation to the SVG for the about page. 

Let me know if I missed anything. If this doesn't sufficiently close the issue, we can go back and forth in the PR before merging it in and I can make adjustments.

### CODE REVIEW

**Comment by baudoinalkali** [comment]
Can we make the right hand illustration bigger? Similar proportions can be found here: https://chattr.ai/about/. Also the image inside the blue blob should be curved.

**Comment by ogdenstudios** [comment]
We can make the illustration bigger for sure. I'll take another pass at that shortly. 

As for the image border, I would definitely recommend uploading a photoshopped image with the appropriate borders if you want to perfectly mimic its background shape across all browsers. 

We could use [clip-path](https://caniuse.com/?search=clip-path) for CSS, but it doesn't have wide enough support that I'd trust it with that. I think photoshopping to the correct border is the right move here.

**Comment by baudoinalkali** [comment]
Understood, I'll do that.

**Comment by ogdenstudios** [comment]
@baudoinalkali - I've got family stuff through the rest of the night, so I'll probably be wrapping up for now, but I should be able to come back and revisit the image size and layout here tomorrow.

**Comment by baudoinalkali** [comment]
All good, thanks for all the help and enjoy the rest of your weekend!

**Comment by ogdenstudios** [comment]
@baudoinalkali - I think I fixed up the layout here. I had to get pretty fiddly with it in order to hit the image dimensions from the Figma file. The nice thing is it's easy to tweak and play around with if you want to nudge it around at different breakpoints. Let me know what you think on this one!

**Comment by baudoinalkali** [comment]
Looks good!

**Pull request merged**
