### PR TITLE
Resolve 12 pricing feature tooltip

### LINKED ISSUE #12: Pricing Feature/ToolTip Component
Please create the component for this section (image). The content isn't final, what is would be the headings such as Jobs Management, AI Hiring Assistant, Interview Booking, etc. I'm thinking it would be best to set up arrays for them and we can set up the data maps, then just fill in the information afterwards. I attached the images backgrounds. Here is a breakdown on the styling:

Titles (Jobs Management, AI Hiring Assistant): text-xl font-avantbold
Features (Branded Job Portal, Free Job Board Postings Distribution):  font-proximasemi text-xl
Tool tip text: font-proximasemi text-md

Here are the .svgs:

https://drive.google.com/drive/folders/1WUUiYOWUs6K8tpmQtZfSzO1C8zUMaW0N?usp=sharing

### PR DESCRIPTION
**Pull request by ogdenstudios**
Resolves #12 

Hey @baudoinalkali - here's my first pass at a tooltip. It's got the correct typography, the background image. I've got it working on hover, and I also wired this up so it can be focus-able, meaning people on assistive technology and/or phones can access the content without having to hover with a mouse. 

You should take a look at the deploy preview though. The one thing I'm still not confident about is the positioning. I set it so that the top of the tooltip starts at the bottom of its associated item, and it's pushed slightly to the right so people can hover over each and every question mark in sequence, without it covering the next one. 

That positioning is a bit of a departure from the image you posted in the issue, where the tooltip is down and to the right of the question mark. That works fine for the left and middle column, but I wanted to do something that would work across viewports (when we're in a single column layout), and that would work for the right-most column as well. 

We can adjust that as needed, but I wanted to start simple and iterate as needed. Let me know what you think!

### CODE REVIEW

**Comment by baudoinalkali** [comment]
Let me run it by the client to see how married to the positioning they are. Is it possible to have the tooltip fade in? I believe duration-500 is the standard across the rest of the site.

**Comment by ogdenstudios** [comment]
Oh for sure. It's got the default 150ms from tailwind. I'll add the 500ms fade in and hold for feedback.

**Comment by ogdenstudios** [comment]
Pushed up the duration change!

**Comment by baudoinalkali** [comment]
Perfect.

**Pull request merged**
