### PR TITLE
Resolve 7 blurb fix homepage

### LINKED ISSUE #7: Blurb Fix Homepage
Can you refine this? Having to focus on some other things atm. The ideal look is: 
image
How it is currently:
image

I'm working on getting the correct headshot, but let's just ignore the huge chunk in the image.

### PR DESCRIPTION
**Pull request by ogdenstudios**
Hey @baudoinalkali - this is about as close as I think I can get these blurbs without a few more things, or without spending a lot of time fiddling. I'm happy to do the fiddling, but it could take a few hours and I want to run it past you before I spend my time with that.

Overall, I think this is closer, and I will defer to you on some of this based on how precise the client wants us to get to pixel perfect. If they're cool with an approximation of the original design, I think we're in good shape. Otherwise we'll need a little more from them. 

Resolves #7 

## Rounding effect

The rounding effect on these backgrounds is a little more than just border radius, I think. We have a couple of options:

1. The best option in my opinion is to get those backgrounds as SVG and then we can set them up as backgrounds in a containing div and position the text over them.
2. If that's not possible, we could try using [clip path](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/clip-path) to create the effect - but we still want the specs to get it pixel perfect. Otherwise, I can spend some time fiddling with the path values and just try and get close. That's probably sufficient.
3. Kind of like option 1, we could also get those backgrounds as PNGs and put them as backgrounds, but it'll be harder to ensure the text always fits within them than if we used SVG or clip-path. And if we could export them out as images, we would probably have the SVG export available as well, so I don't think we should get hung up here too much. 
4. Finally, we could also just leave as is or tweak it with border radius and see if we can get close enough on its own. I did my best with that here, but didn't want to waste time fiddling right now. Happy to spend more time fiddling if you think that's worth it. 

## Fonts 

1. I bumped up the sizing of the attribution on the quote, but I think that `Beals` logo is an SVG or something. We need that as SVG or image if possible - or whatever font-face they used to construct the logo. One way or another, I don't think we can duplicate the logo without an asset there. 
2. I opened up the quote itself with some more line spacing, but I think the fonts they used in the original are not present in the project. My guess is for the `88%` boldness, we want font-weight 800 or 900. You had that hardcoded, but I don't think we have those font weights loaded in `styles.globals.css`, and I didn't see any source files for them in `public/fonts`. If we could get a wider range of weights, we could probably get closer. 

## Headshot

This looks like we can accomplish it a little closer with border radius, although we still might want to explore `clip-path` on it. One way or another, we probably want a square crop of that headshot. In this PR, I took a square crop of one of the cropped images as an example for now. 

## Positioning/spacing specs

I took my best guess on the positioning and transforms for the intersection of these items, along with the padding. Followed your lead on the utilities you used for it, and I think we're pretty close. If this is close enough for them, I think we're in good shape. If they want it pixel perfect, we're just really gonna need source material, or maybe send time fiddling with values and going back and forth with them on what's precisely correct.

### CODE REVIEW

**Comment by baudoinalkali** [comment]
I can get you an SVG for the blog, wasn’t sure if that was the best way to go about it. I would imagine that would also be the way to go for the headers?

Also for the bealls logo we would use an SVG, I don’t believe I have that, but I’ll see what I can come up with.

**Comment by ogdenstudios** [comment]
Yeah, will you send the SVG along? That would be perfect. You can just check out this branch, add the svg in `components/DesignElements` as a `.svg`, and push to the branch. Then I can pull it down and drop it in.

**Comment by baudoinalkali** [comment]
@ogdenstudios Done.

**Comment by ogdenstudios** [comment]
Excellent. I'll take another look later tonight!

**Pull request merged**
